// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Cycode
{
    internal sealed partial class Vsix
    {
        public const string Id = "Cycode.f2c5020e-67a2-46f8-a888-609412fd59db";
        public const string Name = "Cycode";
        public const string Description = @"The Cycode Visual Studio Extension is a plugin for Visual Studio IDE that helps
users to adopt a shift-left strategy, by enabling code scanning early in the development lifecycle, which could
significantly help businesses avoid costly repairs and potential complications down the line.";
        public const string Language = "en-US";
        public const string Version = "0.0.0";
        public const string Author = "Cycode";
        public const string Tags = "";
    }
}
