name: Build extension
on:
  push:
    branches:
      - main

  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
          vs-version: '[17.0, )'

      - uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: nuget-

      - name: Restore NuGet packages
        run: |
          nuget restore src\extension\Cycode.VisualStudio.Extension.14.0-16.0\Cycode.VisualStudio.Extension.14.0-16.0.csproj
          nuget restore src\extension\Cycode.VisualStudio.Extension.17.0\Cycode.VisualStudio.Extension.17.0.csproj

      - name: Build Cycode.VisualStudio.Extension
        run: |
          msbuild src\extension\Cycode.VisualStudio.Extension.14.0-16.0\Cycode.VisualStudio.Extension.14.0-16.0.csproj /t:Rebuild /p:Configuration=Release
          msbuild src\extension\Cycode.VisualStudio.Extension.17.0\Cycode.VisualStudio.Extension.17.0.csproj /t:Rebuild /p:Configuration=Release
        env:
          DeployExtension: False

      - name: Upload Cycode.VisualStudio.Extension.14.0-16.0 artifact
        uses: actions/upload-artifact@v3
        with:
          name: Cycode.VisualStudio.Extension.14.0-16.0
          if-no-files-found: error
          # We don't use a wildcard pattern here because the path hierarchy is preserved
          path: src/extension/Cycode.VisualStudio.Extension.14.0-16.0/bin/Release/Cycode.VisualStudio.Extension.14.0-16.0.vsix

      - name: Upload Cycode.VisualStudio.Extension.17.0 artifact
        uses: actions/upload-artifact@v3
        with:
          name: Cycode.VisualStudio.Extension.17.0
          if-no-files-found: error
          # We don't use a wildcard pattern here because the path hierarchy is preserved
          path: src/extension/Cycode.VisualStudio.Extension.17.0/bin/Release/Cycode.VisualStudio.Extension.17.0.vsix
